name: Keep-Alive

on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    env:
      RENDER_URL: ${{ secrets.RENDER_URL }}
      HEALTH_ENDPOINT: health

    steps:
      - name: Ping health check endpoint
        run: curl -sS $RENDER_URL/$HEALTH_ENDPOINT > /dev/null